# markdown 
markdown: kramdown
#redcarpet:
#  extensions: ["superscript","tables","with_toc_data","strikethrough","smart"]
#highlighter: pygments

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "City of Los Angeles Open Source  Code Policy"
description: "Achieving Efficiency, Transparency, and Innovation through Reusable and Open Source Software"
baseurl: https://sourcecode.lacity.org
# Uncomment the following line for localhost development at http://127.0.0.1:4000/software/
# baseurl: /software

# GitHub information
org_name: datala
repo_name: open-source-policy 
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: /
 #- text: Introduction
#  url: /introduction/ 


# sass
sass:
  sass_dir: _sass

gems:
  - jekyll-redirect-from
