# markdown 
markdown: kramdown
#redcarpet:
#  extensions: ["superscript","tables","with_toc_data","strikethrough","smart"]
#highlighter: pygments

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Federal Source Code Policy"
description: "Achieving Efficiency, Transparency, and Innovation through Reusable and Open Source Software"
baseurl: https://sourcecode.cio.gov
# Uncomment the following line for localhost development at http://127.0.0.1:4000/software/
# baseurl: /software

# GitHub information
org_name: whitehouse
repo_name: source-code-policy
branch: gh-pages

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: /
- text: 1 - Objectives
  url: /Objectives/
- text: 2 - Scope and Applicability
  url: /Scope/
- text: 3 - Three-Step Software Solutions Analysis
  url: /Three-Step-Software-Solutions-Analysis/
- text: 4 - Government-Wide Code Reuse
  url: /Reuse/
- text: 5 - Open Source Software
  url: /OSS/
- text: 6 - Exceptions to Government Code Reuse
  url: /Exceptions/
- text: 7 - Implementation
  url: /Implementation
- text: Appendix A - Definitions
  url: /AppendixA/
 #- text: Introduction
#  url: /introduction/ 


# sass
sass:
  sass_dir: _sass

gems:
  - jekyll-redirect-from
