# Jekyll config for CityOfLosAngeles/best-practices
title: Los Angeles Open Source Policy
description: >- # this means to ignore newlines until "baseurl:"
  Draft Open Source Policy for the City of Los Angeles. 
baseurl: "/open-source-policy" # the subpath of your site, e.g. /blog
url: "CityOfLosAngeles.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  CityOfLosAngeles

# Build settings
markdown: kramdown
theme: jekyll-theme-slate

plugins:
  - jekyll-readme-index
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
